### ISSUE TITLE
Can't stream mp3 format in icecast2 with HTTPS

### ISSUE THREAD

**Issue by jmarellanocreation** [xiph/ezstream#33] opened 2022-02-20 12:23 UTC
I am able to stream mp3 using HTTP and port 8000. But when I tried to use HTTPS with icecast2 and ezstream, it is not connecting.

If I open https://xxxxxxxxxx.org:8443/stream on my browser, it return,
404 - The file you requested could not be found

If I run ezstream with my configuration, it return,

# ezstream -c /path/ezstream-minimal.xml
ezstream[3829]: /path/ezstream-minimal.xml: world readable
ezstream[3829]: stream: default: connect: [xxxxxxxxxx.org]:8443: error -9: This libshout doesn't support the requested option
ezstream[3829]: initial server connection failed

**Comment by mgrimm** [comment] 2022-08-20 01:29
This is a duplicate of #30 and should be fixed in the develop branch now.

**Closed as completed by mgrimm** 2022-08-20 01:29 UTC
Labels: duplicate
