### ISSUE TITLE
ezstream segfaults at __strlen_avx2 function.

### ISSUE THREAD

**Issue by elonden** [xiph/ezstream#22] opened 2020-09-02 05:53 UTC
For some reason the eztream process segfaults at some stage but I haven;t been able to dig into the underlying cause. Using gdb I was to extract some information and there seems to be an issue where a register is being used which was set to 0 at some stage and then some modulo function gets an invalid reference.

==================
```
Program terminated with signal SIGSEGV, Segmentation fault.
--Type <RET> for more, q to quit, c to continue without paging--
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65		VPCMPEQ (%rdi), %ymm0, %ymm1
```

```
(gdb) disass __strlen_avx2


Dump of assembler code for function __strlen_avx2:
   0x00007f115e9a64b0 <+0>:	endbr64 
   0x00007f115e9a64b4 <+4>:	mov    %edi,%ecx
   0x00007f115e9a64b6 <+6>:	mov    %rdi,%rdx
   0x00007f115e9a64b9 <+9>:	vpxor  %xmm0,%xmm0,%xmm0
   0x00007f115e9a64bd <+13>:	and    $0x3f,%ecx
   0x00007f115e9a64c0 <+16>:	cmp    $0x20,%ecx
   0x00007f115e9a64c3 <+19>:	ja     0x7f115e9a64f0 <__strlen_avx2+64>
** => 0x00007f115e9a64c5 <+21>:	vpcmpeqb (%rdi),%ymm0,%ymm1
```

```
(gdb) i r
rax            0x3                 3
rbx            0x6                 6
rcx            0x0                 0
rdx            0x0                 0
rsi            0x55fc8ed61e69      94543216516713
** rdi            0x0                 0                    <<<<<<<<<<<<<<<
```
```
(gdb) i proc m
Mapped address spaces:

          Start Addr           End Addr       Size     Offset objfile
      0x55fc8ed50000     0x55fc8ed53000     0x3000        0x0 /usr/bin/ezstream
      0x55fc8ed53000     0x55fc8ed61000     0xe000     0x3000 /usr/bin/ezstream
      0x55fc8ed61000     0x55fc8ed66000     0x5000    0x11000 /usr/bin/ezstream
<snip>
      0x7f115e844000     0x7f115e869000    0x25000        0x0 /usr/lib64/libc-2.31.so
      0x7f115e869000     0x7f115e9b9000   0x150000    0x25000 /usr/lib64/libc-2.31.so
      0x7f115e9b9000     0x7f115ea04000    0x4b000   0x175000 /usr/lib64/libc-2.31.so
```

```
(gdb) list __strlen_avx2
37	# endif
38	
39	# define VEC_SIZE 32
40	
41		.section .text.avx,"ax",@progbits
42	ENTRY (STRLEN)
43	# ifdef USE_AS_STRNLEN
44		/* Check for zero length.  */
45		test	%RSI_LP, %RSI_LP
46		jz	L(zero)
47	#  ifdef USE_AS_WCSLEN
48		shl	$2, %RSI_LP
49	#  elif defined __ILP32__
50		/* Clear the upper 32 bits.  */
51		movl	%esi, %esi
52	#  endif
53		mov	%RSI_LP, %R8_LP
54	# endif
55		movl	%edi, %ecx
56		movq	%rdi, %rdx
57		vpxor	%xmm0, %xmm0, %xmm0
58	
59		/* Check if we may cross page boundary with one vector load.  */
60		andl	$(2 * VEC_SIZE - 1), %ecx
61		cmpl	$VEC_SIZE, %ecx
62		ja	L(cros_page_boundary)
63	
64		/* Check the first VEC_SIZE bytes.  */
**65		VPCMPEQ (%rdi), %ymm0, %ymm1**
66		vpmovmskb %ymm1, %eax
67		testl	%eax, %eax
```
===================
Any ideas??

Regards
Erwin

**Comment by petterreinholdtsen** [comment] 2020-09-02 06:49
[Erwin van Londen]
> For some reason the eztream process segfaults at some stage but I
> haven;t been able to dig into the underlying cause. Using gdb I was to
> extract some information and there seems to be an issue where a
> register is being used which was set to 0 at some stage and then some
> modulo function gets an invalid reference.

Do you have a way to reproduce it?  Do you see the same error when
running the program under valgrind?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by mgrimm** [comment] 2020-09-02 10:17
Hi Erwin,

If you can provide a backtrace or steps on how to reproduce this, it would be very helpful. Also, can you check that this is not a duplicate of #16?

Thanks,
-Moritz

**Comment by elonden** [comment] 2020-09-03 00:16
The issue appears when there is no id3 tag in the MP3 file.

```
(gdb) bt full
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
No locals.
#1  0x00005640f717f694 in util_expand_words (in=in@entry=0x5640f8b4eef0 "@a@ - @t@", 
    dicts=dicts@entry=0x7ffe255be930) at util.c:295
        buf = <optimized out>
        tmp = <optimized out>
        buf_len = <optimized out>
        d = 0x7ffe255be950
        i = <optimized out>
        out = <optimized out>
        out_size = <optimized out>
#2  0x00005640f7176110 in mdata_strformat (md=md@entry=0x5640f8b669d0, 
    buf=buf@entry=0x7ffe255be9d0 "Wind Up Toy", bufsize=bufsize@entry=8192, format=0x5640f8b4eef0 "@a@ - @t@")
    at mdata.c:496
        dicts = {{from = 0x5640f7180e4f "@a@", to = 0x0}, {from = 0x5640f71801ec "@b@", to = 0x0}, {
            from = 0x5640f7180e69 "@t@", to = 0x0}, {from = 0x5640f7180f91 "@T@", 
            to = 0x5640f8b50e40 "/home/erwin/Music/Alice Cooper/Spark In The Dark - The Best of Alice Cooper Disc 2/09 Alice Cooper Wind Up Toy.mp3"}, {from = 0x5640f7180ee3 "@s@", to = 0x0}, {from = 0x0, to = 0x0}}
        str = <optimized out>
        ret = <optimized out>
#3  0x00005640f7177702 in stream_set_metadata (s=0x5640f8b583d0, md=0x5640f8b669d0, md_str=0x0) at stream.c:447
        buf = "Wind Up Toy\000 Dance Away\000 [EMI]\000y\000frojack - club mix)\000reatest Hits 1990-2010\000e 12 --Type <RET> for more, q to quit, c to continue without paging--c
Inches", '\000' <repeats 3153 times>...
        shout_md = 0x5640f8b59b20
        ret = <optimized out>
#4  0x00005640f7174b4c in streamFile (stream=0x5640f8b583d0, fileName=0x5640f8b49650 "/home/erwin/Music/Alice Cooper/Spark In The Dark - The Best of Alice Cooper Disc 2/09 Alice Cooper Wind Up Toy.mp3") at ezstream.c:571
        tmp = <optimized out>
        metaData = 0x5640f8b58490 ""
        filepstream = 0x5640f8b58720
        popenFlag = <optimized out>
        songLenStr = 0x0
        ret = <optimized out>
        retval = 0
        songLen = <optimized out>
        md = 0x5640f8b669d0
        startTime = {tv_sec = 94837050599888, tv_nsec = 547418162}
        cfg_stream = 0x5640f8b47df0
        cfg_intake = <optimized out>
        isStdin = <optimized out>
#5  0x00005640f7174d53 in streamPlaylist (stream=0x5640f8b583d0) at ezstream.c:684
        song = 0x5640f8b49650 "/home/erwin/Music/Alice Cooper/Spark In The Dark - The Best of Alice Cooper Disc 2/09 Alice Cooper Wind Up Toy.mp3"
        lastSong = "/home/erwin/Music/Alice Cooper/Spark In The Dark - The Best of Alice Cooper Disc 2/09 Alice Cooper Wind Up Toy.mp3\000ychophobia.mp3\000id' (Studio Outtake).mp3", '\000' <repeats 398 times>...
        cfg_intake = 0x5640f8b48000
#6  0x00005640f717319e in main (argc=<optimized out>, argv=<optimized out>) at ezstream.c:806
        ret = 1
        cont = <optimized out>
        errstr = 0x7f9d7ef204fc <_int_malloc+3196> "\351\201\364\377\377H\215\025؄\023"
        act = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 268435456, sa_restorer = 0x0}
        i = <optimized out>
        cfg_server = 0x5640f8b4b070
        cfg_stream = <optimized out>
        cfg_intake = 0x5640f8b48000

```

That file (or better all of the mp3 files in that folder) did not have an id3 tag and every time it segfaults immediately.
As soon as I update those mp3's with an id3 tag there is no issue whatsoever and ezstream happily streams them.

It appreas ezstream may need a check to see if the result of the @a@ and @T@ values (or any other metadata for matter) actually returns a non-zero/non-null value and skip the metadata logic if it does.

**Comment by elonden** [comment] 2020-09-03 06:03
When removing the <format> parameter in the <metadata> section this issue doesn't happen. It indeed appears to be the same/similar as #16

**Comment by mgrimm** [comment] 2020-09-06 23:15
Thanks for checking; closing this as duplicate. It will be fixed in the next release, and the fix is already in the develop branch.

**Closed by mgrimm** 2020-09-06 23:15 UTC
Labels: bug, duplicate
