### ISSUE TITLE
How to uninstall libshout?

### ISSUE THREAD

**Issue by joaoherberto** [xiph/ezstream#2] opened 2016-08-26 17:23 UTC
I installed libeshout-2.4.1 and now even though I installed libshout2.2.2, when configuring ezstream, it is still only finding 2.4 and continually gives error "requires libshout-2.2.x" . Help...

**Comment by mgrimm** [comment] 2016-09-07 13:50
The error message is misleading (fixed now), since it doesn't require a specific version of libshout other than 2.2.0 _or newer_.

This can be caused by a broken or incomplete libshout installation (missing development header files), or a defect in the ezstream build system.

Please attach config.log for further debugging.

**Closed** 2017-03-03 19:42 UTC

**Comment by mgrimm** [comment] 2017-03-03 19:45
Case gone cold.
